// node-and-vue/frontend/src/pages/Dashboard.vue
<script setup>
import { computed, ref, watch } from 'vue';
import { useRoute } from 'vue-router';
import { LuzmoDashboard } from '@luzmo/vue-embed';

const DASHBOARD_IDS = {
  wallace: '9743e36d-7d9c-4703-bf4c-f347cb85169f',
  michael: '3c47cf45-fcb6-4920-a5a8-b79852519552',
  sales: 'e43545ae-353b-46d8-b96d-bc882e0aaf33',
};

const SALES_REPS = new Set(['dwight', 'jim', 'phyllis', 'stanley', 'andy']);

const NAMES = {
  wallace: 'David',
  michael: 'Michael',
  dwight: 'Dwight',
  jim: 'Jim',
  phyllis: 'Phyllis',
  stanley: 'Stanley',
  andy: 'Andy',
};

const route = useRoute();
const role = computed(() => route.query.role || 'wallace');
const name = computed(() => NAMES[role.value] || 'User');
const dashboardId = computed(() =>
  SALES_REPS.has(role.value)
    ? DASHBOARD_IDS.sales
    : DASHBOARD_IDS[role.value] || DASHBOARD_IDS.wallace
);

const embedConfig = ref(null);
const error = ref(null);

watch(
  role,
  (currentRole) => {
    embedConfig.value = null;
    error.value = null;

    fetch('/api/embed', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ role: currentRole }),
    })
      .then((res) => {
        if (!res.ok) throw new Error(`Server error: ${res.status}`);
        return res.json();
      })
      .then((data) => {
        embedConfig.value = data;
      })
      .catch((err) => {
        error.value = err.message;
      });
  },
  { immediate: true }
);
</script>

<template>
  <nav class="navbar">
    <h2>Here's your Dashboard, {{ name }}</h2>
    <router-link class="switch-profile" to="/">Switch Profile</router-link>
  </nav>

  <div class="embed-container">
    <div v-if="error" class="embed-loading">
      <p>Failed to load dashboard: {{ error }}</p>
    </div>

    <div v-else-if="!embedConfig" class="embed-loading">
      <p>Loading dashboard...</p>
    </div>

    <LuzmoDashboard
      v-else
      :appServer="embedConfig.appServer"
      :apiHost="embedConfig.apiHost"
      :authKey="embedConfig.authKey"
      :authToken="embedConfig.authToken"
      :dashboardId="dashboardId"
    />
  </div>
</template>

// py-and-angular/frontend/src/app/pages/dashboard/dashboard.component.ts
import { Component, OnInit, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { NgxLuzmoDashboardModule } from '@luzmo/ngx-embed';
import { EmbedService, EmbedConfig } from '../../services/embed.service';

const DASHBOARD_IDS: Record<string, string> = {
  wallace: '9743e36d-7d9c-4703-bf4c-f347cb85169f',
  michael: '3c47cf45-fcb6-4920-a5a8-b79852519552',
  sales: 'e43545ae-353b-46d8-b96d-bc882e0aaf33',
};

const SALES_REPS = new Set(['dwight', 'jim', 'phyllis', 'stanley', 'andy']);

const NAMES: Record<string, string> = {
  wallace: 'David',
  michael: 'Michael',
  dwight: 'Dwight',
  jim: 'Jim',
  phyllis: 'Phyllis',
  stanley: 'Stanley',
  andy: 'Andy',
};

@Component({
  selector: 'app-dashboard',
  imports: [RouterLink, NgxLuzmoDashboardModule],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  templateUrl: './dashboard.component.html',
  styleUrl: './dashboard.component.css',
})
export class DashboardComponent implements OnInit {
  role = 'wallace';
  name = 'David';
  dashboardId = DASHBOARD_IDS['wallace'];
  embedConfig: EmbedConfig | null = null;
  error: string | null = null;

  constructor(
    private route: ActivatedRoute,
    private embedService: EmbedService,
  ) {}

  ngOnInit(): void {
    this.route.queryParams.subscribe((params) => {
      this.role = params['role'] || 'wallace';
      this.name = NAMES[this.role] || 'User';
      this.dashboardId = SALES_REPS.has(this.role)
        ? DASHBOARD_IDS['sales']
        : DASHBOARD_IDS[this.role] || DASHBOARD_IDS['wallace'];
      this.loadEmbed();
    });
  }

  private loadEmbed(): void {
    this.embedConfig = null;
    this.error = null;

    this.embedService.getEmbedToken(this.role).subscribe({
      next: (config) => (this.embedConfig = config),
      error: (err) => (this.error = err.message || 'Failed to load dashboard'),
    });
  }
}

<nav class="navbar">
  <h2>Here's your Dashboard, {{ name }}</h2>
  <a class="switch-profile" routerLink="/">Switch Profile</a>
</nav>

<div class="embed-container">
  @if (error) {
    <div class="embed-loading">
      <p>Failed to load dashboard: {{ error }}</p>
    </div>
  }

  @if (!embedConfig && !error) {
    <div class="embed-loading">
      <p>Loading dashboard...</p>
    </div>
  }

  @if (embedConfig) {
    <luzmo-dashboard
      [dashboardId]="dashboardId"
      [authKey]="embedConfig.authKey"
      [authToken]="embedConfig.authToken"
      [appServer]="embedConfig.appServer"
      [apiHost]="embedConfig.apiHost">
    </luzmo-dashboard>
  }
</div>
