// node-and-vue/frontend/src/pages/Dashboard.vue
<script setup>
import { computed, ref, watch } from 'vue';
import { useRoute } from 'vue-router';
import { LuzmoDashboard } from '@luzmo/vue-embed';

const DASHBOARD_IDS = {
  wallace: '9743e36d-7d9c-4703-bf4c-f347cb85169f',
  michael: '3c47cf45-fcb6-4920-a5a8-b79852519552',
  sales: 'e43545ae-353b-46d8-b96d-bc882e0aaf33',
};

const SALES_REPS = new Set(['dwight', 'jim', 'phyllis', 'stanley', 'andy']);

const NAMES = {
  wallace: 'David',
  michael: 'Michael',
  dwight: 'Dwight',
  jim: 'Jim',
  phyllis: 'Phyllis',
  stanley: 'Stanley',
  andy: 'Andy',
};

const route = useRoute();
const role = computed(() => route.query.role || 'wallace');
const name = computed(() => NAMES[role.value] || 'User');
const dashboardId = computed(() =>
  SALES_REPS.has(role.value)
    ? DASHBOARD_IDS.sales
    : DASHBOARD_IDS[role.value] || DASHBOARD_IDS.wallace
);

const embedConfig = ref(null);
const error = ref(null);

watch(
  role,
  (currentRole) => {
    embedConfig.value = null;
    error.value = null;

    fetch('/api/embed', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ role: currentRole }),
    })
      .then((res) => {
        if (!res.ok) throw new Error(`Server error: ${res.status}`);
        return res.json();
      })
      .then((data) => {
        embedConfig.value = data;
      })
      .catch((err) => {
        error.value = err.message;
      });
  },
  { immediate: true }
);
</script>

<template>
  <nav class="navbar">
    <h2>Here's your Dashboard, {{ name }}</h2>
    <router-link class="switch-profile" to="/">Switch Profile</router-link>
  </nav>

  <div class="embed-container">
    <div v-if="error" class="embed-loading">
      <p>Failed to load dashboard: {{ error }}</p>
    </div>

    <div v-else-if="!embedConfig" class="embed-loading">
      <p>Loading dashboard...</p>
    </div>

    <LuzmoDashboard
      v-else
      :appServer="embedConfig.appServer"
      :apiHost="embedConfig.apiHost"
      :authKey="embedConfig.authKey"
      :authToken="embedConfig.authToken"
      :dashboardId="dashboardId"
    />
  </div>
</template>

// py-and-react/frontend/src/pages/Dashboard.jsx
import { useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { LuzmoDashboardComponent } from '@luzmo/react-embed';

const roleConfig = {
  wallace: {
    name: 'David Wallace \u2022 Corporate Overview',
    desc: 'Big-picture KPIs: revenue, growth, branch comparisons.',
    kpis: ['Company Revenue', 'Top Branches', 'YoY Growth', 'Profit Margin'],
  },
  michael: {
    name: 'Michael Scott \u2022 Regional Manager',
    desc: 'Scranton vs other branches. Trends, vibes, and bragging rights.',
    kpis: [
      'Branch Rankings',
      'Regional Sales Trend',
      'Customer Retention',
      "That's what she said",
    ],
  },
  dwight: {
    name: 'Dwight Schrute \u2022 Top Sales Rep',
    desc: 'Daily performance, best sellers, personal scoreboards.',
    kpis: [
      "Today's Sales",
      'Top Products',
      'Leaderboard',
      'Beets Sold (Secret KPI)',
    ],
  },
};

export default function Dashboard() {
  const [searchParams] = useSearchParams();
  const role = searchParams.get('role') || 'wallace';
  const config = roleConfig[role] || roleConfig.wallace;

  const [embedConfig, setEmbedConfig] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    setEmbedConfig(null);
    setError(null);

    fetch('/api/embed', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ role }),
    })
      .then((res) => {
        if (!res.ok) throw new Error(`Server error: ${res.status}`);
        return res.json();
      })
      .then((data) => setEmbedConfig(data))
      .catch((err) => setError(err.message));
  }, [role]);

  return (
    <>
      <nav className="navbar">
        <h2>Dashboard</h2>
        <Link className="switch-profile" to="/">
          Switch Profile
        </Link>
      </nav>

      <section className="role-banner">
        <h1>{config.name}</h1>
        <p>{config.desc}</p>
      </section>

      <section className="kpis">
        {config.kpis.map((kpi) => (
          <div key={kpi} className="kpi-card">
            <h3>{kpi}</h3>
            <p>Metric placeholder</p>
          </div>
        ))}
      </section>

      <section className="dashboard-section">
        <h2>Embedded Luzmo Dashboard</h2>

        <div className="embed-container">
          {error && (
            <div className="embed-loading">
              <p>Failed to load dashboard: {error}</p>
            </div>
          )}

          {!embedConfig && !error && (
            <div className="embed-loading">
              <p>Loading dashboard...</p>
            </div>
          )}

          {embedConfig && (
            <LuzmoDashboardComponent
              appServer={embedConfig.appServer}
              apiHost={embedConfig.apiHost}
              authKey={embedConfig.authKey}
              authToken={embedConfig.authToken}
              dashboardId={embedConfig.dashboardId}
            />
          )}
        </div>
      </section>
    </>
  );
}
